workflows:
  build-and-deploy:
    name: Güvenli Okul Otomasyon Sistemi Mobil Uygulaması
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      android_signing:
        - keystore_reference
      vars:
        DOTNET_VERSION: "8.0"
    scripts:
      - name: Install .NET SDK
        script: |
          wget https://dot.net/v1/dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --channel $DOTNET_VERSION --install-dir $CM_BUILD_DIR/dotnet
      
      - name: Setup Android SDK
        script: |
          echo "y" | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platforms;android-33"
          echo "y" | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "build-tools;33.0.0"
      
      - name: Install MAUI Workloads
        script: |
          $CM_BUILD_DIR/dotnet/dotnet workload install android maui --source https://api.nuget.org/v3/index.json
      
      - name: Build Android APK
        script: |
          $CM_BUILD_DIR/dotnet/dotnet publish goosorgtr_mobil.csproj -f:net7.0-android -c:Release

    artifacts:
      - bin/Release/**/goosorgtr_mobil*.apk
