workflows:
  build-and-deploy:
    name: Güvenli Okul Otomasyon Sistemi Mobil Uygulaması
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        DOTNET_VERSION: "8.0"
    scripts:
      - name: List Directory Structure
        script: |
          pwd
          ls -la
      
      - name: Install .NET SDK
        script: |
          wget https://dot.net/v1/dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --channel $DOTNET_VERSION --install-dir $CM_BUILD_DIR/dotnet
      
      - name: Setup Android SDK
        script: |
          echo "y" | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platforms;android-33"
          echo "y" | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "build-tools;33.0.0"
      
      - name: Install MAUI Workloads
        script: |
          $CM_BUILD_DIR/dotnet/dotnet workload install android maui --source https://api.nuget.org/v3/index.json
      
      - name: List installed workloads
        script: |
          $CM_BUILD_DIR/dotnet/dotnet workload list

      - name: Build Android APK
        script: |
          # Proje dosyasının tam yolunu bulalım
          PROJECT_FILE=$(find . -name "*.csproj" -type f)
          echo "Found project file: $PROJECT_FILE"
          
          if [ -n "$PROJECT_FILE" ]; then
            $CM_BUILD_DIR/dotnet/dotnet publish "$PROJECT_FILE" -f:net8.0-android -c:Release -v:diagnostic
          else
            echo "No .csproj file found!"
            exit 1
          fi

    artifacts:
      - bin/Release/**/**.apk
