workflows:
  build-and-deploy:
    name: Build and Deploy MAUI App
    max_build_duration: 120
    instance_type: mac_mini_m2
    scripts:
      - name: Install .NET SDK
        script: |
          wget https://dot.net/v1/dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --install-dir $CM_BUILD_DIR/dotnet

      - name: Install MAUI Workloads
        script: |
          $CM_BUILD_DIR/dotnet/dotnet workload install maui --source https://aka.ms/dotnet6/nuget/index.json

      - name: Build the app
        script: |
          $CM_BUILD_DIR/dotnet/dotnet build YourProject.csproj -c Release

      - name: Publish the app
        script: |
          $CM_BUILD_DIR/dotnet/dotnet publish YourProject.csproj -c Release -o output_directory
